using System;

namespace MoneyTask
{
	public class Currency
	{
		private int num;
		private String code;
		public static Currency[] types = {
			new Currency("ALL",	8),
			new Currency("DZD",	12),
			new Currency("ARS",	32),
			new Currency("AUD",	36),
			new Currency("BSD",	44),
			new Currency("BHD",	48),
			new Currency("BDT",	50),
			new Currency("AMD",	51),
			new Currency("BBD",	52),
			new Currency("BMD",	60),
			new Currency("BTN",	64),
			new Currency("BOB",	68),
			new Currency("BWP",	72),
			new Currency("BZD",	84),
			new Currency("SBD",	90),
			new Currency("BND",	96),
			new Currency("MMK",	104),
			new Currency("BIF",	108),
			new Currency("KHR",	116),
			new Currency("CAD",	124),
			new Currency("CVE",	132),
			new Currency("KYD",	136),
			new Currency("LKR",	144),
			new Currency("CLP",	152),
			new Currency("CNY",	156),
			new Currency("COP",	170),
			new Currency("KMF",	174),
			new Currency("CRC",	188),
			new Currency("HRK",	191),
			new Currency("CUP",	192),
			new Currency("CZK",	203),
			new Currency("DKK",	208),
			new Currency("DOP",	214),
			new Currency("ETB",	230),
			new Currency("ERN",	232),
			new Currency("FKP",	238),
			new Currency("FJD",	242),
			new Currency("DJF",	262),
			new Currency("GMD",	270),
			new Currency("GIP",	292),
			new Currency("GTQ",	320),
			new Currency("GNF",	324),
			new Currency("GYD",	328),
			new Currency("HTG",	332),
			new Currency("HNL",	340),
			new Currency("HKD",	344),
			new Currency("HUF",	348),
			new Currency("ISK",	352),
			new Currency("INR",	356),
			new Currency("IDR",	360),
			new Currency("IRR",	364),
			new Currency("IQD",	368),
			new Currency("ILS",	376),
			new Currency("JMD",	388),
			new Currency("JPY",	392),
			new Currency("KZT",	398),
			new Currency("JOD",	400),
			new Currency("KES",	404),
			new Currency("KPW",	408),
			new Currency("KRW",	410),
			new Currency("KWD",	414),
			new Currency("KGS",	417),
			new Currency("LAK",	418),
			new Currency("LBP",	422),
			new Currency("LSL",	426),
			new Currency("LRD",	430),
			new Currency("LYD",	434),
			new Currency("MOP",	446),
			new Currency("MWK",	454),
			new Currency("MYR",	458),
			new Currency("MVR",	462),
			new Currency("MRO",	478),
			new Currency("MUR",	480),
			new Currency("MXN",	484),
			new Currency("MNT",	496),
			new Currency("MDL",	498),
			new Currency("MAD",	504),
			new Currency("OMR",	512),
			new Currency("NAD",	516),
			new Currency("NPR",	524),
			new Currency("ANG",	532),
			new Currency("AWG",	533),
			new Currency("VUV",	548),
			new Currency("NZD",	554),
			new Currency("NIO",	558),
			new Currency("NGN",	566),
			new Currency("NOK",	578),
			new Currency("PKR",	586),
			new Currency("PAB",	590),
			new Currency("PGK",	598),
			new Currency("PYG",	600),
			new Currency("PEN",	604),
			new Currency("PHP",	608),
			new Currency("QAR",	634),
			new Currency("RUB",	643),
			new Currency("RWF",	646),
			new Currency("SHP",	654),
			new Currency("STD",	678),
			new Currency("SAR",	682),
			new Currency("SCR",	690),
			new Currency("SLL",	694),
			new Currency("SGD",	702),
			new Currency("VND",	704),
			new Currency("SOS",	706),
			new Currency("ZAR",	710),
			new Currency("SSP",	728),
			new Currency("SZL",	748),
			new Currency("SEK",	752),
			new Currency("CHF",	756),
			new Currency("SYP",	760),
			new Currency("THB",	764),
			new Currency("TOP",	776),
			new Currency("TTD",	780),
			new Currency("AED",	784),
			new Currency("TND",	788),
			new Currency("UGX",	800),
			new Currency("MKD",	807),
			new Currency("EGP",	818),
			new Currency("GBP",	826),
			new Currency("TZS",	834),
			new Currency("USD",	840),
			new Currency("UYU",	858),
			new Currency("UZS",	860),
			new Currency("WST",	882),
			new Currency("YER",	886),
			new Currency("TWD",	901),
			new Currency("CUC",	931),
			new Currency("TMT",	934),
			new Currency("GHS",	936),
			new Currency("VEF",	937),
			new Currency("SDG",	938),
			new Currency("UYI",	940),
			new Currency("RSD",	941),
			new Currency("MZN",	943),
			new Currency("AZN",	944),
			new Currency("RON",	946),
			new Currency("CHE",	947),
			new Currency("CHW",	948),
			new Currency("TRY",	949),
			new Currency("XAF",	950),
			new Currency("XCD",	951),
			new Currency("XOF",	952),
			new Currency("XPF",	953),
			new Currency("XBA",	955),
			new Currency("XBB",	956),
			new Currency("XBC",	957),
			new Currency("XBD",	958),
			new Currency("XAU",	959),
			new Currency("XDR",	960),
			new Currency("XAG",	961),
			new Currency("XPT",	962),
			new Currency("XTS",	963),
			new Currency("XPD",	964),
			new Currency("XUA",	965),
			new Currency("ZMW",	967),
			new Currency("SRD",	968),
			new Currency("MGA",	969),
			new Currency("COU",	970),
			new Currency("AFN",	971),
			new Currency("TJS",	972),
			new Currency("AOA",	973),
			new Currency("BYR",	974),
			new Currency("BGN",	975),
			new Currency("CDF",	976),
			new Currency("BAM",	977),
			new Currency("EUR",	978),
			new Currency("MXV",	979),
			new Currency("UAH",	980),
			new Currency("GEL",	981),
			new Currency("BOV",	984),
			new Currency("PLN",	985),
			new Currency("BRL",	986),
			new Currency("CLF",	990),
			new Currency("XSU",	994),
			new Currency("USN",	997),
			new Currency("USS",	998),
			new Currency("XXX",	999)
		};

		private Currency (String code, int num)
		{
			this.num = num;
			this.code = code;
		}

		public int Num {
			get {
				return num;
			}
		}

		public String Code {
			get {
				return code;
			}
		}

		public static Currency getByNum(int num) {
			foreach (Currency c in types) {
				if (c.Num == num) {
					return c;
				}
			}
			return null;
		}
	}
}

